<ul id="magesquare-popup-messages" style="display: none">
<?php foreach ($this->getData('popup_messenger')->getPopups(true) as $id => $message) : ?>
    <li id="magesquare-popup-<?php echo $id ?>">
        <div class="magesquare__popup-title"><?php echo $this->escapeHtml($message['title']) ?></div>
        <div class="magesquare__popup-text">
            <pre><?php echo $this->escapeHtml($message['text']) ?></pre>
        </div>
    </li>
<?php endforeach; ?>
</ul>

<script type="text/javascript">
require([
    'jquery',
    'Magento_Ui/js/modal/alert'
], function ($, alert) {
    $('.magesquare__action-info-message').click(function(e) {
        e.preventDefault();
        var context = '#magesquare-popup-' + $(this).attr('data-target');
        alert({
            title: $('.magesquare__popup-title', context).html(),
            content: $('.magesquare__popup-text', context).html()
        });
    });
});
</script>
